"""Research-backed citations for Stratum findings.

Each finding type maps to a one-line statistic and source.
Citations are appended to the attack-scenario description
from the DX patch. They are NOT generated by LLM -- they are
hardcoded strings from published research.

Sources are verified as of Feb 2026. Update quarterly.
"""
from __future__ import annotations

import dataclasses


@dataclasses.dataclass
class Citation:
    stat: str       # The one-line statistic
    source: str     # Attribution (author/org, title, date)
    url: str        # Verification URL


CITATIONS: dict[str, Citation] = {
    "STRATUM-001": Citation(
        stat="Tool poisoning attacks succeed 37% avg across 20 LLM agents. Best models refuse <3% of the time.",
        source="MCPTox benchmark -- arxiv:2508.14925",
        url="https://arxiv.org/abs/2508.14925",
    ),
    "STRATUM-002": Citation(
        stat='OWASP ranks "Human-Agent Trust Exploitation" as a top-10 agentic risk for 2026.',
        source="OWASP Agentic Top 10, ASI09",
        url="https://genai.owasp.org/resource/owasp-top-10-for-agentic-applications-for-2026/",
    ),
    "STRATUM-003": Citation(
        stat="6 of 12 MCP attack categories achieve 100% success rate when code execution is available.",
        source='arxiv:2509.24272 -- "When MCP Servers Attack"',
        url="https://arxiv.org/abs/2509.24272",
    ),
    "STRATUM-005": Citation(
        stat="In Sept 2025, a malicious MCP on npm silently copied every email to an attacker for 2+ weeks.",
        source="Koi Security / Snyk -- postmark-mcp incident",
        url="https://snyk.io/blog/malicious-mcp-server-on-npm-postmark-mcp-harvests-emails/",
    ),
    "STRATUM-006": Citation(
        stat="72% of MCP plugins expose sensitive operations. 5+ servers -> >70% composite exploit probability.",
        source="Pynt -- 281 MCP configurations analyzed, 2025",
        url="https://www.pynt.io/resources-hub/mcp-security-research-2025",
    ),
    "STRATUM-007": Citation(
        stat="Agents follow malicious tool instructions 37-73% of the time with no guardrail between input and API.",
        source="MCPTox benchmark -- arxiv:2508.14925",
        url="https://arxiv.org/abs/2508.14925",
    ),
    "STRATUM-008": Citation(
        stat="In simulation, a single agent failure poisoned 87% of downstream decisions within 4 hours.",
        source="Galileo AI multi-agent failure research, Dec 2025",
        url="",
    ),
    "STRATUM-009": Citation(
        stat="32% of developers cite reliability as the #1 barrier to production agents -- not security, not cost.",
        source="LangChain State of Agent Engineering, 2025 -- 1,300 respondents",
        url="https://www.langchain.com/state-of-agent-engineering",
    ),
    "ENV-001": Citation(
        stat="9% of real-world MCP configs are immediately exploitable -- exposed secrets make it worse.",
        source="Pynt -- 281 MCP configurations analyzed, 2025",
        url="https://www.pynt.io/resources-hub/mcp-security-research-2025",
    ),
}


def get_citation(finding_id: str) -> Citation | None:
    """Return the citation for a finding ID, or None."""
    return CITATIONS.get(finding_id)
