"""Visual risk score bar renderer with optional percentile benchmark."""
from __future__ import annotations

import json
import os

from stratum.models import Finding, Severity

# Benchmark data file path (generated by batch/ecosystem_report.py)
_BENCHMARK_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "benchmarks.json")
_benchmark_cache: dict[int, float] | None = None


def render_risk_bar(
    risk_score: int, findings: list[Finding], width: int = 40,
) -> list[str]:
    """Render a visual risk bar as a list of Rich-formatted strings.

    Output (without benchmarks):
     RISK SCORE ████████████████████████████░░░░░░░░░░  69 / 100
                ▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔
                2 critical · 7 high · 4 medium

    Output (with benchmarks):
     RISK SCORE ████████████████████████████░░░░░░░░░░  69 / 100  (73rd percentile)
                ▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔
                2 critical · 7 high · 4 medium
    """
    filled = int(width * risk_score / 100)
    empty = width - filled

    if risk_score <= 30:
        color = "green"
    elif risk_score <= 60:
        color = "yellow"
    elif risk_score <= 80:
        color = "orange1"
    else:
        color = "red"

    bar = "\u2588" * filled + "\u2591" * empty
    underline = "\u2594" * width

    # Severity counts
    sev_counts: dict[str, int] = {}
    for f in findings:
        s = f.severity.value
        sev_counts[s] = sev_counts.get(s, 0) + 1

    parts: list[str] = []
    for s in ("CRITICAL", "HIGH", "MEDIUM", "LOW"):
        if sev_counts.get(s, 0) > 0:
            parts.append(f"{sev_counts[s]} {s.lower()}")
    severity_line = " \u00b7 ".join(parts)

    # Percentile benchmark (if data available)
    percentile_str = ""
    pctile = get_percentile(risk_score)
    if pctile is not None:
        suffix = _ordinal_suffix(int(pctile))
        percentile_str = f"  [dim]({int(pctile)}{suffix} percentile)[/dim]"

    return [
        "",
        f" [{color}]RISK SCORE {bar}[/{color}]  [bold]{risk_score} / 100[/bold]{percentile_str}",
        f"            [dim]{underline}[/dim]",
        f"            {severity_line}",
        "",
    ]


def get_percentile(risk_score: int) -> float | None:
    """Get the percentile for a risk score from benchmark data.

    Returns None if benchmark data is not available.
    """
    benchmarks = _load_benchmarks()
    if not benchmarks:
        return None
    return benchmarks.get(risk_score)


def _load_benchmarks() -> dict[int, float]:
    """Load benchmark percentile data from the data file."""
    global _benchmark_cache
    if _benchmark_cache is not None:
        return _benchmark_cache

    try:
        with open(_BENCHMARK_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
        _benchmark_cache = {int(k): float(v) for k, v in data.items()}
    except (OSError, json.JSONDecodeError, ValueError):
        _benchmark_cache = {}

    return _benchmark_cache


def _ordinal_suffix(n: int) -> str:
    """Get ordinal suffix for a number (1st, 2nd, 3rd, 4th, etc.)."""
    if 11 <= n % 100 <= 13:
        return "th"
    remainder = n % 10
    if remainder == 1:
        return "st"
    if remainder == 2:
        return "nd"
    if remainder == 3:
        return "rd"
    return "th"
